site_name: Claire Nelson
nav:
  - Home: index.md
  -  Analysis of Data Job Market Trends Using Python: code-examples.md
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/clairenelson2002/clairenelson2002'
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
  palette: 
    #Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Dark mode
    primary: cyan
    accent: grey

  #Light Mode
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Light mode
    primary: cyan
    accent: white
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
  


  